# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Makecli < Formula
  desc "makecli — agentic development platform cli"
  homepage "https://github.com/qfeius/makecli"
  version "0.5.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qfeius/makecli/releases/download/v0.5.10/makecli_0.5.10_darwin_amd64.tar.gz"
      sha256 "cd0cb2039f6b45f669130260b8da4a63b759f0b1031bcc0fc913f48280ed9af8"

      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qfeius/makecli/releases/download/v0.5.10/makecli_0.5.10_darwin_arm64.tar.gz"
      sha256 "959508ee4d69385a0b3b202b4687a90ef4e4ad23140ee4d2b4c774222847be0d"

      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.5.10/makecli_0.5.10_linux_amd64.tar.gz"
      sha256 "0b7674532453fee6e40dd4746358aca3b2d906c5ff47746808798b400c2c4a72"
      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.5.10/makecli_0.5.10_linux_arm64.tar.gz"
      sha256 "549543531393a1d2f613bb117d1f19ff57099b157dd7cd63555db315e0abbd32"
      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  test do
    system "#{bin}/makecli version"
  end
end
